# Generated by Django 4.2.1 on 2023-05-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimParty',
            fields=[
                ('partyKey', models.IntegerField(primary_key=True, serialize=False)),
                ('partyId', models.IntegerField(max_length=32)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('CityName', models.CharField(max_length=100)),
                ('Region', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
            ],
        ),
    ]
